### PR TITLE
fix: context-aware named param conversion

### LINKED ISSUE #510: Support graphile migrate placeholders
Graphile migrate uses placeholder for some variables. They are compiled to the matching env variables at runtime. 

Image

It would be great if the pg-lsp would support that, or at least allow to disable some rule that causes this error.

### PR DESCRIPTION
**Pull request by psteinroe**
we were blindly converting named parameters to positional parameters. but the latter is only valid as a literal, and not as an identifier.

statements like

```sql
grant usage on schema public, app_public, app_hidden to :DB_ROLE;
```

are not valid when converted to

```sql
grant usage on schema public, app_public, app_hidden to $1;
```

i went a bit back and forth on this and decided the easiest way to fix this is to convert to identifiers like `a` if the previous non-trivia token is one of a set list of tokens. We will probably have a bunch of edge cases here but fixing them should be as easy as adding a keyword to the list.

now, we convert to

```sql
grant usage on schema public, app_public, app_hidden to a;
```

closes #510

### CODE REVIEW

File: crates/pgt_workspace/src/workspace/server/pg_query.rs [hunk 1]
```diff
@@ -146,17 +179,45 @@ pub fn convert_to_positional_params(text: &str) -> String {
...
+/// Generates a deterministic identifier based on the given index.
+fn deterministic_identifier(idx: usize) -> String {
+    let iteration = idx / ALPHABET.len();
+    let pos = idx % ALPHABET.len();
+
+    format!(
+        "{}{}",
+        ALPHABET[pos],
+        if iteration > 0 {
+            deterministic_identifier(iteration - 1)
```
Comment (juleswritescode) [inline crates/pgt_workspace/src/workspace/server/pg_query.rs:201]: i love me a good recursion

File: crates/pgt_lexer/src/lexer.rs [hunk 2]
```diff
@@ -143,7 +143,7 @@ impl<'a> Lexer<'a> {
                         }
                         _ => {}
                     };
-                    SyntaxKind::POSITIONAL_PARAM
+                    SyntaxKind::NAMED_PARAM
```
Comment (juleswritescode) [inline crates/pgt_lexer/src/lexer.rs:146]: das war n bug nehm ich an?

**Review by juleswritescode — APPROVED** [review]
nice! 

So the typechecker doesn't properly check whether a role exists or not? 
I would've expected it to complain about the "missing role `a`"

**Comment by psteinroe** [comment]
> nice! 
> 
> 
> 
> So the typechecker doesn't properly check whether a role exists? 
> 
> I would've expected it to complain about the "missing role `a`" 

The typechecker just runs on DML statements and such replacement are less of an issue there. but at some point someone will report it too I guess. If that happens, we can find another solution for it. 😅👍🏼

File: crates/pgt_workspace/src/workspace/server/pg_query.rs (hunk 1 above)
Comment (psteinroe) [reply crates/pgt_workspace/src/workspace/server/pg_query.rs:201]: das kam sogar ohne Claude 😂

File: crates/pgt_lexer/src/lexer.rs (hunk 2 above)
Comment (psteinroe) [reply crates/pgt_lexer/src/lexer.rs:146]: Ja, allerdings kein wichtiger für die Statement Splitter Logik deshalb kam es nie raus
