### PR TITLE
fix: add support for named param type `$name`

### LINKED ISSUE #474: add support for `$name` in the lexer

### PR DESCRIPTION
**Pull request by psteinroe**
## What kind of change does this PR introduce?

closes #474 

from https://github.com/supabase-community/postgres-language-server/issues/454#issuecomment-3177986456

### CODE REVIEW

File: crates/pgt_tokenizer/src/lib.rs [hunk 1]
```diff
@@ -186,9 +186,29 @@ impl Cursor<'_> {
...
-                    self.dollar_quoted_string()
+                    // Get the start sequence of the dollar quote, i.e., 'foo' in $foo$hello$foo$
+                    // if ident does not continue and there is no terminating dollar
+                    // sign, we have a positional param `$name`
+                    let mut start = vec![];
+                    loop {
+                        match self.first() {
+                            '$' => {
+                                self.bump();
+                                break self.dollar_quoted_string(start);
```
Comment (juleswritescode) [inline crates/pgt_tokenizer/src/lib.rs:197]:
```suggestion
                                return self.dollar_quoted_string(start);
```

File: crates/pgt_tokenizer/src/lib.rs [hunk 2]
```diff
@@ -186,9 +186,29 @@ impl Cursor<'_> {
...
+                            }
+                            c if is_ident_cont(c) => {
+                                self.bump();
+                                start.push(c);
+                            }
+                            _ => {
+                                break TokenKind::NamedParam {
```
Comment (juleswritescode) [inline crates/pgt_tokenizer/src/lib.rs:204]:
```suggestion
                                return TokenKind::NamedParam {
```

File: crates/pgt_tokenizer/src/lib.rs (hunk 1 above)
Comment (juleswritescode) [reply crates/pgt_tokenizer/src/lib.rs:197]: hat mich kurz irritiert, weil der breaked value ja auch aus der obrigen fn returned wird

File: crates/pgt_tokenizer/src/lib.rs (hunk 2 above)
Comment (psteinroe) [reply crates/pgt_tokenizer/src/lib.rs:204]: this would actually behave differently. we need break, and the value is then returned from the loop. with return, we would return the value from the function.
