### PR TITLE
fix: dont point to 404 in config schema

### LINKED ISSUE #319: postgrestools init config JSON schema URL results in 404
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application.
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

I just created my first Postgres Language Server configuration file using the CLI and it created a configuration file that listed "https://pgtools.dev/schemas/0.3.1/schema.json" as the JSON Schema URL. Unfortunately, this URL results in a 404.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install the latest postgrestools CLI via NPM
2. Run `postgrestools init`
3. See error in generated output

## Expected behavior

I had expected the Schema URL to exist.

## Screenshots

Image

## System information

- OS: macOS
- IDE: VS Code
- Package Manager: Yarn

### PR DESCRIPTION
**Pull request by psteinroe**
fixes #319 until we have versioned docs setup by

- preferring node_modules schema if available
- uses `latest` if the CLI does not have a version set (`0.0.0`)
- uses `VERSION` if a version is set

### CODE REVIEW

File: crates/pgt_workspace/src/configuration.rs [hunk 1]
```diff
@@ -170,12 +170,12 @@ pub fn create_config(
...
-        let schema_path = Path::new("./node_modules/@postgrestools/postgrestools/schema.json");
-        let options = OpenOptions::default().read(true);
-        if fs.open_with_options(schema_path, options).is_ok() {
-            configuration.schema = schema_path.to_str().map(String::from);
-        }
+    let node_schema_path = Path::new("./node_modules/@postgrestools/postgrestools/schema.json");
+    let options = OpenOptions::default().read(true);
+    if fs.open_with_options(node_schema_path, options).is_ok() {
+        configuration.schema = node_schema_path.to_str().map(String::from);
+    } else if VERSION == "0.0.0" {
```
Comment (juleswritescode) [inline crates/pgt_workspace/src/configuration.rs:177]: kannst du noch n comment hinzufügen wann VERSION 0.0.0 ist? Ich hab's schon wieder vergessen 😢

**Review by juleswritescode — APPROVED** [review]

File: crates/pgt_workspace/src/configuration.rs (hunk 1 above)
Comment (juleswritescode) [inline crates/pgt_workspace/src/configuration.rs:177]:
```suggestion
    } else if VERSION == "0.0.0" {
    // VERSION is 0.0.0 if it has not been explicitly set (e.g local dev, as fallback) 
```

Comment (juleswritescode) [reply crates/pgt_workspace/src/configuration.rs:177]: grade in der desc gelesen 👍🏻  passt das so?
